// components/TutorialCard.vue
<script setup lang="ts">
interface TutorialCardProps {
  path: string;
  id: string;
  title: string;
  timeToRead: string;
  description: string;
  author: string;
  date: string;
  tags: string[];
}

const props = defineProps<TutorialCardProps>();
</script>

<template>
  <main>
    <div class="mt-4 mx-3">
      <a :href="props.path">
        <div
          class="border border-gray-400 rounded-lg p-4 flex flex-col justify-between leading-normal hover:shadow-lg dark:hover:shadow-gray-600"
        >
          <div class="mb-8">
            <div class="font-bold text-xl">
              {{ props.title }}
            </div>
            <p class="mb-2 text-gray-400">{{ props.timeToRead }}</p>
            <p class="text-base">{{ props.description }}</p>
          </div>
          <div class="flex items-center">
            <div class="text-sm flex flex-grow">
              <div class="flex flex-row flex-grow-0">
                <p class="mr-2">{{ props.author }}</p>
                <span class="mr-2">⚬</span>
                <time>{{ props.date }}</time>
              </div>
              <div class="hidden md:flex flex-row flex-grow justify-end">
                <span
                  v-for="(tag, index) in props.tags"
                  :key="index"
                  class="px-4 mt-auto mx-1 rounded-lg bg-cyan-700 text-white items-center"
                >
                  {{ tag }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
  </main>
</template>

// src/components/cards/TutorialCard.tsx
import { Link } from 'gatsby'
import React from 'react'
import { GatsbyImage, IGatsbyImageData } from 'gatsby-plugin-image'
import { Tag } from '../tag'

interface Props {
	path: string
	id: string
	title: string
	timeToRead: string
	description: string
	gatsbyImageData: IGatsbyImageData
	author: string
	date: string
	tags: string[]
}

export const TutorialCard = ({
	path,
	id,
	title,
	timeToRead,
	description,
	gatsbyImageData,
	author,
	date,
	tags,
}: Props): React.ReactElement => {
	return (
		<Link to={path} key={id}>
			<div className="mt-3 mx-3">
				<div className="border border-gray-400 bg-white rounded-lg p-4 flex flex-col justify-between leading-normal hover:shadow-lg">
					<div className="mb-8">
						<div className="text-gray-900 font-bold text-xl">{title}</div>
						<p className="text-gray-600 mb-2">{timeToRead} min read</p>
						<p className="text-gray-700 text-base">{description}</p>
					</div>
					<div className="flex items-center">
						<GatsbyImage
							image={gatsbyImageData}
							alt="Avatar"
							className="w-10 h-10 rounded-full mr-4"
						/>
						<div className="text-sm flex flex-grow">
							<div className="flex-grow-0">
								<p className="text-gray-900 leading-none">{author}</p>
								<time className="text-gray-600">{date}</time>
							</div>
							<div className="hidden md:flex flex-row flex-grow justify-end">
								{tags.map((tagName: string) => {
									return <Tag tagName={tagName} />
								})}
							</div>
						</div>
					</div>
				</div>
			</div>
		</Link>
	)
}
