// pages/legal.vue
<script setup lang="ts">
useHead({
  title: 'Legal ',
});
</script>

<template>
    <div id="impressum-en" class="container flex flex-col md:justify-between mx-auto mb-10">
				<h1 class="text-2xl mb-3">Legal Disclosure / Impressum</h1>
				Information in accordance with Section 5 TMG
				<br />
                <br />
				Simon Scholz
				<br />
				Uckermarkweg 1️⃣2️⃣a
				<br />
				2️⃣2️⃣4️⃣1️⃣5️⃣ Hamburg
				<br />
                <br />
				<h2 class="text-xl">Contact Information</h2>
				Telephone: +4️⃣9️⃣ 1️⃣7️⃣6️⃣ - 4️⃣3️⃣ 6️⃣2️⃣2️⃣ 0️⃣6️⃣0️⃣
				<br />
				E-Mail:
				<a href="mailto:opensource.simon@gmail.com">
					opensource.simonⓐⓣgmail.com
				</a>
				<br />
				Internet address:
				<a
					href="https://simonscholz.github.io/"
					target="_blank"
					rel="noreferrer"
				>
					https://simonscholz.github.io/
				</a>
				<br />
				<br />
				<h2>Disclaimer</h2>
				Accountability for content
				<br />
				The contents of our pages have been created with the utmost care.
				However, we cannot guarantee the contents' accuracy, completeness or
				topicality. According to statutory provisions, we are furthermore
				responsible for our own content on these web pages. In this matter,
				please note that we are not obliged to monitor the transmitted or saved
				information of third parties, or investigate circumstances pointing to
				illegal activity. Our obligations to remove or block the use of
				information under generally applicable laws remain unaffected by this as
				per §§ 8 to 10 of the Telemedia Act (TMG).
				<br />
				<br />
				Accountability for links
				<br />
				Responsibility for the content of external links (to web pages of third
				parties) lies solely with the operators of the linked pages. No
				violations were evident to us at the time of linking. Should any legal
				infringement become known to us, we will remove the respective link
				immediately.
				<br />
				<br />
				Copyright
				<br /> Our web pages and their contents are subject to German copyright
				law. Unless expressly permitted by law, every form of utilizing,
				reproducing or processing works subject to copyright protection on our
				web pages requires the prior consent of the respective owner of the
				rights. Individual reproductions of a work are only allowed for private
				use. The materials from these pages are copyrighted and any unauthorized
				use may violate copyright laws.
				<br />
				<br />
				<h2>Google Analytics</h2>
				<p>
					This website uses Google Analytics, a web analytics service provided
					by Google, Inc. (»Google«). Google Analytics uses cookies, which are
					text files placed on your computer, to help the website analyze how
					users use the site. The information generated by the cookie about your
					use of the website (including your IP address) will be transmitted to
					and stored by Google on servers in the United States. In case of
					activation of the IP anonymization, Google will truncate/anonymize the
					last octet of the IP address for Member States of the European Union
					as well as for other parties to the Agreement on the European Economic
					Area. Only in exceptional cases, the full IP address is sent to and
					shortened by Google servers in the USA. On behalf of the website
					provider Google will use this information for the purpose of
					evaluating your use of the website, compiling reports on website
					activity for website operators and providing other services relating
					to website activity and internet usage to the website provider. Google
					will not associate your IP address with any other data held by Google.
					By using this website, you consent to the processing of data about you
					by Google in the manner and for the purposes set out above.
				</p>
				<h2>How to prevent being tracked by Google Analytics</h2>
				<p>
					<ul>
						<li>
							You may refuse the use of cookies by selecting the appropriate
							settings on your browser. However, please note that if you do
							this, you may not be able to use the full functionality of this
							website.
						</li>
						<li>
							Furthermore you can prevent Google's collection and use of data
							(cookies and IP address) by downloading and installing the browser
							plug-in available under
							<a
								href="https://tools.google.com/dlpage/gaoptout?hl=en"
								target="_blank"
								rel="noreferrer"
							>
								https://tools.google.com/dlpage/gaoptout?hl=en
							</a>
							.
						</li>
					</ul>
				</p>
				<i>Source: </i>
				<a href="http://www.translate-24h.de" target="_blank" rel="noreferrer">
					Deutsch-Englisch Übersetzungen
				</a>
				<br />
				<a
					href="https://language-boutique.de/naithani/blogpost/impressum-auf-englisch.html"
					target="_blank"
					rel="noreferrer"
				>
					Language Boutique.de/Muster-Impressum
				</a>
				<br />
			</div>
</template>

<style scoped>
p {
  @apply mt-6;
}

h1 {
  @apply text-3xl;
}
</style>

// src/pages/legal.tsx
import React from 'react'
import { SEO } from '../components/SEO'

const Legal = ({ data }: any): React.ReactElement => {
	return (
		<>
			<SEO title="Legal" />

			<div id="impressum-en" className="blog-post-content m-2 markdown">
				<h1>Legal Disclosure / Impressum</h1>
				Information in accordance with Section 5 TMG
				<br />
				Simon Scholz
				<br />
				Uckermarkweg 1️⃣2️⃣a
				<br />
				2️⃣2️⃣4️⃣1️⃣5️⃣ Hamburg
				<br />
				<h2>Contact Information</h2>
				Telephone: +4️⃣9️⃣ 1️⃣7️⃣6️⃣ - 4️⃣3️⃣ 6️⃣2️⃣2️⃣ 0️⃣6️⃣0️⃣
				<br />
				E-Mail:{' '}
				<a href="mailto:opensource.simon@gmail.com">
					opensource.simonⓐⓣgmail.com
				</a>
				<br />
				Internet address:{' '}
				<a
					href="https://simonscholz.github.io/"
					target="_blank"
					rel="noreferrer"
				>
					https://simonscholz.github.io/
				</a>
				<br />
				<br />
				<h2>Disclaimer</h2>
				Accountability for content
				<br />
				The contents of our pages have been created with the utmost care.
				However, we cannot guarantee the contents' accuracy, completeness or
				topicality. According to statutory provisions, we are furthermore
				responsible for our own content on these web pages. In this matter,
				please note that we are not obliged to monitor the transmitted or saved
				information of third parties, or investigate circumstances pointing to
				illegal activity. Our obligations to remove or block the use of
				information under generally applicable laws remain unaffected by this as
				per §§ 8 to 10 of the Telemedia Act (TMG).
				<br />
				<br />
				Accountability for links
				<br />
				Responsibility for the content of external links (to web pages of third
				parties) lies solely with the operators of the linked pages. No
				violations were evident to us at the time of linking. Should any legal
				infringement become known to us, we will remove the respective link
				immediately.
				<br />
				<br />
				Copyright
				<br /> Our web pages and their contents are subject to German copyright
				law. Unless expressly permitted by law, every form of utilizing,
				reproducing or processing works subject to copyright protection on our
				web pages requires the prior consent of the respective owner of the
				rights. Individual reproductions of a work are only allowed for private
				use. The materials from these pages are copyrighted and any unauthorized
				use may violate copyright laws.
				<br />
				<br />
				<h2>Google Analytics</h2>
				<p>
					This website uses Google Analytics, a web analytics service provided
					by Google, Inc. (»Google«). Google Analytics uses cookies, which are
					text files placed on your computer, to help the website analyze how
					users use the site. The information generated by the cookie about your
					use of the website (including your IP address) will be transmitted to
					and stored by Google on servers in the United States. In case of
					activation of the IP anonymization, Google will truncate/anonymize the
					last octet of the IP address for Member States of the European Union
					as well as for other parties to the Agreement on the European Economic
					Area. Only in exceptional cases, the full IP address is sent to and
					shortened by Google servers in the USA. On behalf of the website
					provider Google will use this information for the purpose of
					evaluating your use of the website, compiling reports on website
					activity for website operators and providing other services relating
					to website activity and internet usage to the website provider. Google
					will not associate your IP address with any other data held by Google.
					By using this website, you consent to the processing of data about you
					by Google in the manner and for the purposes set out above.
				</p>
				<h2>How to prevent being tracked by Google Analytics</h2>
				<p>
					<ul>
						<li>
							You may refuse the use of cookies by selecting the appropriate
							settings on your browser. However, please note that if you do
							this, you may not be able to use the full functionality of this
							website.
						</li>
						<li>
							Furthermore you can prevent Google’s collection and use of data
							(cookies and IP address) by downloading and installing the browser
							plug-in available under
							<a
								href="https://tools.google.com/dlpage/gaoptout?hl=en"
								target="_blank"
								rel="noreferrer"
							>
								https://tools.google.com/dlpage/gaoptout?hl=en
							</a>
							.
						</li>
					</ul>
				</p>
				<i>Source: </i>
				<a href="http://www.translate-24h.de" target="_blank" rel="noreferrer">
					Deutsch-Englisch Übersetzungen
				</a>{' '}
				<br />
				<a
					href="https://language-boutique.de/naithani/blogpost/impressum-auf-englisch.html"
					target="_blank"
					rel="noreferrer"
				>
					Language Boutique.de/Muster-Impressum
				</a>{' '}
				<br />
			</div>
		</>
	)
}

export default Legal
